joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_manager_ns: ''
controller_list:
    - name: mobile_dual_arm/right_arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint_right
        - r_joint_1
        - r_joint_2
        - r_joint_3
        - r_joint_4
        - r_joint_5
        - r_joint_6
        - r_joint_7
    - name: mobile_dual_arm/left_arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint_left
        - l_joint_1
        - l_joint_2
        - l_joint_3
        - l_joint_4
        - l_joint_5
        - l_joint_6
        - l_joint_7       

   
    # - name: mobile_dual_arm/right_hand_controller
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   default: true
    #   joints:
    #     - r_joint_7
    #     - r_tool_joint
    # - name: mobile_dual_arm/left_hand_controller
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   joints:
    #     - l_joint_7
    #     - l_tool_joint
# initial:  # Define initial robot poses.
#   - group: right_arm
#     pose: home
#   - group: left_arm
#     pose: home
#   - group: right_hand
#     pose: home
#   - group: left_hand
#     pose: home

